name: calendars

services:
  backend-dev:
    entrypoint: ["/bin/sh", "-c"]
    command: ["python manage.py runserver 0.0.0.0:8000"]
    userns_mode: keep-id
    environment:
      - DJANGO_CONFIGURATION=MosaCloud
    volumes:
      - ./src/backend:/app:Z
      - ./data/static:/data/static:Z
      - ./data/translations.json:/data/translations.json:Z
      - /app/.venv
    depends_on:
      postgresql:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started
      celery-dev:
        condition: service_started
      caldav:
        condition: service_started

  celery-dev:
    entrypoint: ["/bin/sh", "-c"]
    command: ["celery -A calendars.celery_app worker -l DEBUG"]
    userns_mode: keep-id
    environment:
      - DJANGO_CONFIGURATION=MosaCloud
    volumes:
      - ./src/backend:/app:Z
      - ./data/static:/data/static:Z
      - ./data/translations.json:/data/translations.json:Z
      - /app/.venv

  frontend-dev:
    userns_mode: keep-id
    volumes:
      - ./src/frontend/:/home/frontend/:Z
      - /home/frontend/node_modules
      - /home/frontend/apps/calendars/node_modules

  caldav:
    volumes:
      - ./docker/sabredav/server.php:/var/www/sabredav/server.php:Z
      - ./docker/sabredav/src:/var/www/sabredav/src:Z
      - ./docker/sabredav/sql:/var/www/sabredav/sql:Z
      - ./docker/sabredav/init-database.sh:/usr/local/bin/init-database.sh:Z
